CREATE TABLE USD美金 (
    id INTEGER NOT NULL AUTO_INCREMENT,
    date VARCHAR(255) NOT NULL,
    rate DOUBLE NOT NULL
);
CREATE TABLE GBP英鎊 (
    id INTEGER NOT NULL AUTO_INCREMENT,
    date VARCHAR(255) NOT NULL,
    rate DOUBLE NOT NULL
);
CREATE TABLE EUR歐元 (
    id INTEGER NOT NULL AUTO_INCREMENT,
    date VARCHAR(255) NOT NULL,
    rate DOUBLE NOT NULL
);